import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000/api';
const nav=['Overview','Diagnostics','Analytics','Drain health','Alerts','Sensor data','Experiments','Digital twin','Simulation','System status','About'];
const Card=({title,children})=><section className="card"><h3>{title}</h3>{children}</section>;
const Metric=({label,value,unit})=><div className="metric"><span className="muted">{label}</span><strong>{value??'—'} <small>{unit}</small></strong></div>;
function Chart({rows,field,color='#38d3b5'}){if(!rows?.length)return <p className="muted">No telemetry history available.</p>;let vals=rows.map(r=>Number(r[field]||0)),max=Math.max(...vals,1),points=vals.map((v,i)=>`${i/(vals.length-1||1)*100},${100-v/max*85-8}`).join(' ');return <svg className="chart" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={points} fill="none" stroke={color} strokeWidth="2"/></svg>}
function App(){const[page,setPage]=useState('Overview'),[data,setData]=useState(null),[status,setStatus]=useState(null),[health,setHealth]=useState(null),[history,setHistory]=useState([]),[alerts,setAlerts]=useState([]),[drain,setDrain]=useState(null),[experiments,setExperiments]=useState([]),[experiment,setExperiment]=useState(null),[label,setLabel]=useState('normal'),[sim,setSim]=useState({blockage_severity:.4,initial_water_level:35,inflow:25}),[result,setResult]=useState(null),[query,setQuery]=useState(''),[pageNo,setPageNo]=useState(1),[error,setError]=useState(false);
 const load=async()=>{try{let [a,b,c,d,e,f,g]=await Promise.all(['sensors/latest','status','sensors/health','sensors/history?limit=100','alerts','drain-health','experiments'].map(x=>fetch(API+'/'+x).then(r=>{if(!r.ok)throw Error();return r.json()})));setData(a);setStatus(b);setHealth(c);setHistory(d.items||[]);setAlerts(e.items||[]);setDrain(f);setExperiments(g.items||[]);setError(false)}catch{setError(true)}};
 useEffect(()=>{load();let id=setInterval(load,15000);return()=>clearInterval(id)},[]);
 const d=data?.diagnosis||{}, stale=status?.freshness?.status!=='FRESH'||error;
 async function run(){let r=await fetch(API+'/simulation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(sim)});setResult(await r.json())}
 async function startExperiment(){let r=await fetch(API+'/experiments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label})});if(r.ok){setExperiment(await r.json());load()}}
 async function stopExperiment(){if(!experiment)return;await fetch(API+'/experiments/'+experiment.id+'/stop',{method:'POST'});setExperiment(null);load()}
 const filtered=useMemo(()=>history.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[history,query]), rows=filtered.slice((pageNo-1)*10,pageNo*10);
 return <><header><div className="brand"><span>◈</span> DrainGuard <b>AI</b></div><div className={'mode '+(stale?'bad':'')}>● {stale?'OFFLINE / STALE':status?.mode?.toUpperCase()||'CONNECTING'} · <strong>{status?.mode==='live'?'LIVE':'DEMO MODE'}</strong></div></header><div className="layout"><aside>{nav.map(n=><button className={page===n?'active':''} onClick={()=>{setPage(n);setPageNo(1)}}>{n}</button>)}</aside><main><div className="heading"><div><p className="eyebrow">DRAINAGE NODE / NODE-A</p><h1>{page}</h1><p className="muted">{stale?'Telemetry is stale or unavailable. Showing last known values only.':'Telemetry-backed operational view · Last update '+(status?.freshness?.age_seconds??'—')+'s ago'}</p></div><a className="export" href={API+'/export.csv'}>Export CSV</a></div>
 {page==='Overview'&&<><div className="grid stats"><Card title="Drain health"><strong className="big">{drain?.score??'—'}<small>/100</small></strong><p className="muted">Defined weighted index</p></Card><Card title="Blockage risk"><strong className="big">{d.risk_score!=null?Math.round(d.risk_score*100):'—'}<small>%</small></strong><p className="pill">{d.condition||'Awaiting telemetry'}</p></Card><Card title="Sensor reliability"><strong className="big">{d.sensor_reliability!=null?Math.round(d.sensor_reliability*100):'—'}<small>%</small></strong><p className="muted">{health?.cross_sensor_consistency||'—'}</p></Card><Card title="Data freshness"><strong className="big">{status?.freshness?.status||'—'}</strong><p className="muted">{status?.source||'No source'}</p></Card></div><div className="grid"><Card title="Live sensor snapshot"><div className="readings"><Metric label="Flow 1" value={data?.flow1} unit="pulses/s"/><Metric label="Flow 2" value={data?.flow2} unit="pulses/s"/><Metric label="Difference" value={data?.flow_difference??d.features?.flow_difference} unit="pulses/s"/><Metric label="Water level" value={data?.water_level} unit="%"/></div></Card><Card title="AI diagnosis"><h2>{d.condition||'Awaiting data'}</h2><p>{d.recommended_action||'Connect a device or ingest a reading.'}</p>{(d.reasons||[]).map(x=><div className="reason">• {x}</div>)}</Card></div></>}
 {page==='Diagnostics'&&<div className="grid"><Card title="Structured diagnosis"><h2>{d.condition||'—'}</h2><Metric label="Confidence" value={d.confidence!=null?Math.round(d.confidence*100):'—'} unit="%"/><Metric label="Severity" value={d.severity}/><p>{d.recommended_action}</p>{(d.reasons||[]).map(x=><div className="reason">• {x}</div>)}</Card><Card title="Sensor health"><Health sensors={health?.sensors}/><p className="muted">Cross-sensor consistency: {health?.cross_sensor_consistency||'—'}</p></Card></div>}
 {page==='Analytics'&&<div className="grid"><Card title="Flow history"><Chart rows={history} field="flow1"/><Chart rows={history} field="flow2" color="#f4b45d"/></Card><Card title="Water level and flow difference"><Chart rows={history} field="water_level" color="#66a9ff"/><Chart rows={history} field="flow_difference" color="#f07878"/></Card></div>}
 {page==='Drain health'&&<Card title={'Drain health index: '+(drain?.score??'—')+'/100'}><div className="bars">{Object.entries(drain?.dimensions||{}).map(([k,v])=><div><span>{k.replaceAll('_',' ')}</span><b style={{width:v+'%'}}></b><em>{v}</em></div>)}</div><p className="muted">{drain?.formula}</p></Card>}
 {page==='Alerts'&&<Card title="Current alerts">{alerts.length?alerts.map(a=><div className="alert"><b>{a.severity}</b><span>{a.condition}: {a.message}</span></div>):<p className="muted">No active alerts from current telemetry.</p>}</Card>}
 {page==='Sensor data'&&<Card title="Telemetry history"><input className="search" placeholder="Search readings..." value={query} onChange={e=>setQuery(e.target.value)}/><table><thead><tr>{['timestamp','flow1','flow2','flow_difference','flow_ratio','water_level','source'].map(x=><th>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr>{['timestamp','flow1','flow2','flow_difference','flow_ratio','water_level','source'].map(x=><td>{typeof r[x]==='number'?Number(r[x]).toFixed(2):r[x]}</td>)}</tr>)}</tbody></table><div className="pager"><button onClick={()=>setPageNo(Math.max(1,pageNo-1))}>Previous</button> Page {pageNo} / {Math.max(1,Math.ceil(filtered.length/10))} <button onClick={()=>setPageNo(Math.min(Math.ceil(filtered.length/10)||1,pageNo+1))}>Next</button></div></Card>}
 {page==='Experiments'&&<div className="grid"><Card title="Experiment recorder"><p className="muted">Samples are recorded from submitted telemetry only; no values are generated.</p><label>Physical experiment type<select value={label} onChange={e=>setLabel(e.target.value)} disabled={!!experiment}>{['NORMAL','PARTIAL_BLOCKAGE','SEVERE_BLOCKAGE','RISING_WATER','SENSOR_FAULT','NOISY_SENSOR','RECOVERY'].map(x=><option key={x}>{x}</option>)}</select></label>{experiment?<button className="primary" onClick={stopExperiment}>Stop experiment</button>:<button className="primary" onClick={startExperiment}>Start experiment</button>}<p>{experiment?`Recording experiment #${experiment.id} (${experiment.label})`:'Not recording'}</p></Card><Card title="Recorded experiments">{experiments.length?experiments.map(e=><div className="alert"><b>{e.label}</b><span>{e.status} · {e.sample_count||0} samples</span></div>):<p className="muted">No experiments recorded.</p>}</Card></div>}
 {page==='Digital twin'&&<Card title="Live digital twin"><div className="twin"><div>FLOW 1<br/><b>{data?.flow1??'—'}</b></div><i>→</i><div>PIPE / RESTRICTION<br/><b>{d.condition||'—'}</b></div><i>→</i><div>FLOW 2<br/><b>{data?.flow2??'—'}</b></div><i>↓</i><div>RESERVOIR<br/><b>{data?.water_level??'—'}%</b></div><i>↓</i><div>PUMP<br/><b>{data?.pump_status??'—'}</b></div></div><p className="muted">State follows actual telemetry and rule diagnosis; no animated fictional values.</p></Card>}
 {page==='Simulation'&&<Card title="Controlled what-if simulation"><p className="warning">SIMULATION / DEVELOPMENT MODE — rule scenario estimate, not a trained prediction.</p>{[['blockage_severity','Blockage severity'],['initial_water_level','Initial water level'],['inflow','Inflow / rainfall']].map(([k,l])=><label>{l}<input type="range" min="0" max="100" value={sim[k]*(k==='blockage_severity'?100:1)} onChange={e=>setSim({...sim,[k]:+e.target.value/(k==='blockage_severity'?100:1)})}/><span>{sim[k]}</span></label>)}<button className="primary" onClick={run}>Run simulation</button>{result&&<div className="result"><h2>{result.predicted_water_level}% predicted water level</h2><p>Risk: <b>{result.predicted_risk}</b></p><p>{result.note}</p></div>}</Card>}
 {page==='System status'&&<div className="grid"><Card title="Connectivity"><Health sensors={{API:stale?'STALE':'HEALTHY',database:status?.database||'—',model:status?.model_status||'—'}}/><p>Mode: <b>{status?.mode||'—'}</b></p><p>Source: {status?.source||'—'}</p></Card><Card title="Model information"><h2>Rule-based fallback</h2><p className="muted">Awaiting labeled real training data. No accuracy claims are displayed.</p></Card></div>}
 {page==='About'&&<Card title="About DrainGuard AI"><h2>Trustworthy drainage intelligence</h2><p>DrainGuard combines ESP32/Blynk telemetry, explicit sensor-health checks, explainable rule fusion and a documented drain-health index.</p><p className="muted">Safety hardware remains controlled by the existing firmware. The AI layer is decision support only.</p></Card>}</main></div></>}
 function Health({sensors}){return <div className="healthlist">{Object.entries(sensors||{}).map(([k,v])=><div><span>{k}</span><b className={v==='HEALTHY'?'ok':'bad'}>{v}</b></div>)}</div>}createRoot(document.getElementById('root')).render(<App/>)
